#!/usr/bin/env bash
# Script to build one of uosc binaries.
# Requirements: go, upx (if compressing)
# Usage: tools/build <name> [-c]
# <name> can be: intl, ziggy
# -c enables binary compression with upx (only needed for builds being released)

abort() {
	echo "Error: $1"
	exit 1
}

if [ ! -d "$PWD/src" ]; then
	abort "'src' directory not found. Make sure this script is run in uosc's repository root as current working directory."
fi

elif [ $1 == "intl" ]; then
	export GOARCH="amd64"
	$src="./src/intl/intl.go"
	$out_dir="./tools"

	echo "Building for Windows..."
	export GOOS="windows"
	go build -ldflags "-s -w" -o "$out_dir/intl.exe" $src

	echo "Building for Linux..."
	export GOOS="linux"
	go build -ldflags "-s -w" -o "$out_dir/intl-linux" $src

	echo "Building for MacOS..."
	export GOOS="darwin"
	go build -ldflags "-s -w" -o "$out_dir/intl-darwin" $src

	if [ $2 == "-c" ]; then
		echo "Compressing binaries..."
		upx --brute "$out_dir/intl.exe"
		upx --brute "$out_dir/intl-linux"
		upx --brute "$out_dir/intl-darwin"
	fi

	unset GOARCH
	unset GOOS

elif [ $1 == "ziggy" ]; then
	export GOARCH="amd64"
	$src = "./src/ziggy/ziggy.go"
	$out_dir = "./dist/scripts/uosc/bin"

	if [ ! -d $out_dir ]; then
		mkdir -pv $out_dir
	fi

	echo "Building for Windows..."
	export GOOS="windows"
	go build -ldflags "-s -w" -o "$out_dir/ziggy-windows.exe" $src

	echo "Building for Linux..."
	export GOOS="linux"
	go build -ldflags "-s -w" -o "$out_dir/ziggy-linux" $src

	echo "Building for MacOS..."
	export GOOS="darwin"
	go build -ldflags "-s -w" -o "$out_dir/ziggy-darwin" $src

	if [ $2 == "-c" ]; then
		echo "Compressing binaries..."
		upx --brute "$out_dir/ziggy-windows.exe"
		upx --brute "$out_dir/ziggy-linux"
		upx --brute "$out_dir/ziggy-darwin"
	fi

	unset GOARCH
	unset GOOS

else
	echo "Tool to build one of uosc binaries. Requires go to be installed and in path."
	echo "Requirements: go, upx (if compressing)"
	echo "Usage: tools/build <name> [-c]"
	echo "<name> can be: intl, ziggy"
	echo "-c enables binary compression (requires upx)"
fi
